# Strings

In [2]:
'Hello my name is    Lefteris'.split()

['Hello', 'my', 'name', 'is', 'Lefteris']

In [4]:
a = 'Hello    my      name     is    Lefteris'.split()

In [5]:
a

['Hello', 'my', 'name', 'is', 'Lefteris']

In [6]:
' '.join(a)

'Hello my name is Lefteris'

# Dictionaries

In [7]:
phones = {}

In [8]:
phones["Dimitris"] = 222222

In [9]:
phones["Maria"] = 333333
phones["Takis"] = 45353635

In [10]:
print(phones)

{'Dimitris': 222222, 'Maria': 333333, 'Takis': 45353635}


In [11]:
for name, number in phones.items():
    print("The phone number of %s is %d" % (name, number))


The phone number of Dimitris is 222222
The phone number of Maria is 333333
The phone number of Takis is 45353635


In [12]:
del phones["Maria"]
print(phones)

{'Dimitris': 222222, 'Takis': 45353635}


# Functions

In [13]:
def my_function():
    print("Hello world !");

In [14]:
my_function()

Hello world !


In [15]:
def my_sum(a,b):
    return (a+b)

In [16]:
my_sum(12, 45)

57

In [17]:
def f(n):
    return n/2, n//2

In [18]:
a, b = f(11)
print(a,b)

5.5 5


### Functions

In [19]:
def fact(N):
    print("Computing factorial for N=", N);
    if(N==1):
        return 1;
    return N*fact(N-1);

In [20]:
fact(2)

Computing factorial for N= 2
Computing factorial for N= 1


2

In [21]:
fact(15)

Computing factorial for N= 15
Computing factorial for N= 14
Computing factorial for N= 13
Computing factorial for N= 12
Computing factorial for N= 11
Computing factorial for N= 10
Computing factorial for N= 9
Computing factorial for N= 8
Computing factorial for N= 7
Computing factorial for N= 6
Computing factorial for N= 5
Computing factorial for N= 4
Computing factorial for N= 3
Computing factorial for N= 2
Computing factorial for N= 1


1307674368000

# List Comprehension

In [22]:
x = []
for ch in 'BioInformatics':
    x.append(ch);
print(x)

['B', 'i', 'o', 'I', 'n', 'f', 'o', 'r', 'm', 'a', 't', 'i', 'c', 's']


In [23]:
x2 = [ ch for ch in 'BioInformatics']
print(x2)

['B', 'i', 'o', 'I', 'n', 'f', 'o', 'r', 'm', 'a', 't', 'i', 'c', 's']


In [25]:
x = [2,54,67,2,657,87,4,234,654,65,76,43,23465,45,56,54,4]
s = 0
for i in x:
    if i%2 == 1:
        s+= i;
s    

24429

In [26]:
sum([i for i in x if i%2 == 1])

24429

# Lambda Functions

In [27]:
def f(x):
    return(x/2)

In [28]:
f(4)

2.0

In [29]:
f2 = lambda x : x/2

In [30]:
f2(10)

5.0

# NumPy

In [31]:
import numpy as np

In [33]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [34]:
np.zeros(23)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [36]:
np.arange(12342, 12350)

array([12342, 12343, 12344, 12345, 12346, 12347, 12348, 12349])

In [37]:
A = np.ones((2,3))
B = np.zeros((4,3))

In [38]:
np.concatenate([A,B])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.concatenate([B,A])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.concatenate([B,A], axes = 1)

TypeError: concatenate() got an unexpected keyword argument 'axes'

In [41]:
A = np.ones((4,1))

In [42]:
A

array([[1.],
       [1.],
       [1.],
       [1.]])

In [44]:
np.concatenate([B,A], axis = 1)

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [47]:
rnd = np.random.random()

In [51]:
rnd

0.9750590063183144

In [53]:
np.random.random((10, 3))

array([[0.63859083, 0.15400441, 0.08607778],
       [0.45348377, 0.2199284 , 0.17886965],
       [0.58007195, 0.26548978, 0.51716291],
       [0.91928909, 0.73350025, 0.69614111],
       [0.7282861 , 0.31076854, 0.79425298],
       [0.80529677, 0.67171939, 0.996278  ],
       [0.68276558, 0.46039008, 0.81085007],
       [0.60377982, 0.98477792, 0.25059703],
       [0.14364373, 0.56836419, 0.75153987],
       [0.60663112, 0.19204132, 0.7633398 ]])

In [55]:
rnd = np.random.random((10, 3)) * 100

In [60]:
rnd.reshape(5,-1)

array([[98.95903222, 85.85166356, 27.40429139,  5.58201902, 29.13976261,
        61.25443824],
       [56.66131534, 28.2935572 ,  5.11311067, 56.55084398, 74.36493823,
         2.21157003],
       [82.26217102, 24.23297486, 87.1423932 , 78.34680503, 64.13769861,
        72.69840547],
       [57.00402725, 66.09794271, 13.95636432, 68.76250808, 87.46841159,
        15.63786638],
       [25.90388185, 52.85773875, 23.53164714, 71.05802384, 91.1302127 ,
        66.56423101]])

In [61]:
rnd

array([[98.95903222, 85.85166356, 27.40429139],
       [ 5.58201902, 29.13976261, 61.25443824],
       [56.66131534, 28.2935572 ,  5.11311067],
       [56.55084398, 74.36493823,  2.21157003],
       [82.26217102, 24.23297486, 87.1423932 ],
       [78.34680503, 64.13769861, 72.69840547],
       [57.00402725, 66.09794271, 13.95636432],
       [68.76250808, 87.46841159, 15.63786638],
       [25.90388185, 52.85773875, 23.53164714],
       [71.05802384, 91.1302127 , 66.56423101]])

In [62]:
rnd.T

array([[98.95903222,  5.58201902, 56.66131534, 56.55084398, 82.26217102,
        78.34680503, 57.00402725, 68.76250808, 25.90388185, 71.05802384],
       [85.85166356, 29.13976261, 28.2935572 , 74.36493823, 24.23297486,
        64.13769861, 66.09794271, 87.46841159, 52.85773875, 91.1302127 ],
       [27.40429139, 61.25443824,  5.11311067,  2.21157003, 87.1423932 ,
        72.69840547, 13.95636432, 15.63786638, 23.53164714, 66.56423101]])

In [63]:
rnd*5

array([[494.79516112, 429.25831781, 137.02145694],
       [ 27.91009508, 145.69881303, 306.27219118],
       [283.30657672, 141.46778601,  25.56555337],
       [282.7542199 , 371.82469113,  11.05785016],
       [411.31085509, 121.16487429, 435.71196602],
       [391.73402517, 320.68849307, 363.49202736],
       [285.02013623, 330.48971354,  69.78182158],
       [343.81254038, 437.34205794,  78.18933192],
       [129.51940925, 264.28869377, 117.65823572],
       [355.29011918, 455.65106349, 332.82115506]])

In [64]:
np.sqrt(rnd)

array([[9.94781545, 9.26561728, 5.23491083],
       [2.36262968, 5.39812584, 7.82652146],
       [7.52737108, 5.31916884, 2.26121885],
       [7.52002952, 8.62351078, 1.48713484],
       [9.06984956, 4.92269996, 9.33500901],
       [8.85137306, 8.00860154, 8.52633599],
       [7.55010114, 8.13006413, 3.73582177],
       [8.29231621, 9.35245484, 3.95447422],
       [5.08958563, 7.27033278, 4.85094291],
       [8.42959215, 9.54621457, 8.15869052]])

In [65]:
np.isnan(rnd)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])